In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.4.1+cu121


# Intro to tensors

Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
# vector 
vector = torch.tensor([7,7])

In [6]:
vector.ndim

1

In [7]:
# shape is 2 by one element 
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[4,5],[5,6]])
MATRIX , MATRIX.ndim, MATRIX.shape

(tensor([[4, 5],
         [5, 6]]),
 2,
 torch.Size([2, 2]))

In [9]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [10]:
TENSOR.ndim

3

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [12]:
# Create a random tensor of size (1,3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.1705, 0.8329, 0.5158, 0.4736],
         [0.9271, 0.9175, 0.1840, 0.0802],
         [0.6091, 0.6330, 0.8578, 0.6170]]])

In [13]:
random_tensor.ndim, random_tensor.shape

(3, torch.Size([1, 3, 4]))

In [14]:
# create a random tensor with similear shape to an image
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zeros and ones

In [15]:
# create all zeros tensor
zeros = torch.zeros(size=(3,4))
zeros.ndim, zeros.shape

(2, torch.Size([3, 4]))

In [16]:
ones = torch.ones(size=(3,4))
ones.ndim, ones.shape

(2, torch.Size([3, 4]))

In [17]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [18]:
# use torch.range()
# start, end, step
ott = torch.arange(0,10,2)
ott

tensor([0, 2, 4, 6, 8])

In [19]:
# creating tensors like another array
tenzeros = torch.zeros_like(ott)
tenzeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

In [20]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None,
                                              device=None,
                                              requires_grad=False)
float_32_tensor.device

device(type='cpu')

In [21]:
float_16 = float_32_tensor.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [22]:
float_16 * float_32_tensor

tensor([ 9., 36., 81.])

In [23]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32) 
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [24]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [25]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information From Tensors

1. Get dataype tensor.dtype
2. Get shape tensor.shape
3. Get device tensor.device

### Manipulating Tensors (tensor operations)

* Addition 
* Substraction
* Multiplication(element-vise)
* Division
* Matrix Multiplication

In [26]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [27]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [28]:
tensor - 10

tensor([-9, -8, -7])

In [29]:
torch.mul(tensor,10)

tensor([10, 20, 30])

## Matrix Multiplication

Two ways:
1. Element Vise
2. Matirx multiplication( dot product )

In [30]:
# Element Vise
tensor * tensor 

tensor([1, 4, 9])

In [31]:
%%time
torch.matmul(tensor, tensor), tensor

CPU times: user 464 μs, sys: 173 μs, total: 637 μs
Wall time: 2.75 ms


(tensor(14), tensor([1, 2, 3]))

### One of the most common erros in deep learning: shape errors

In [34]:
# torch.matmul(torch.rand(3,2),torch.rand(3,2)) # Error
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[1.1320, 0.8397],
        [1.3620, 0.7999]])

In [37]:
torch_A = torch.tensor([[1,2],[3,4],[5,6]])
torch_B = torch.tensor([[7,10],[8,11],[9,12]])

# torch.matmul(torch_A,torch_B) # Error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### Manipulate Shapes

tensor.T will transpose the matrix 

In [38]:
torch.matmul(torch_A.T,torch_B)

tensor([[ 76, 103],
        [100, 136]])

### Finding the min, max , mean, sum, etc(tensor aggregation)

In [44]:
x = torch.arange(0, 100 , 10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [41]:
# find Min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [42]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [46]:
# torch.mean() require tensor of float32
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [47]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding positional min max

In [49]:
x.argmin(), x.argmax()
# Returns the index postion of the min , max element

(tensor(0), tensor(9))

### Reshaping, Stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a an input tensosr of cetain shape but keep the same merory as the original tensor
* stacking - combine multiple tensors on top of each other  or side by side (hstack)
* squeeze - removes all '1' dimensions from tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [60]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [61]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
# change the view 
z = x.view(1,9)
z, z.shape
# here z shares the same memory as x so changing z means changing x or vice versa

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))