In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.5.1+cu124


# Intro to tensors

Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
# vector 
vector = torch.tensor([7,7])

In [6]:
vector.ndim

1

In [7]:
# shape is 2 by one element 
vector.shape

torch.Size([2])

In [11]:
MATRIX = torch.tensor([[4,5],[5,6]])
MATRIX , MATRIX.ndim, MATRIX.shape

(tensor([[4, 5],
         [5, 6]]),
 2,
 torch.Size([2, 2]))

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

In [15]:
# Create a random tensor of size (1,3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.2469, 0.9785, 0.8527, 0.4130],
         [0.5435, 0.5213, 0.0630, 0.3616],
         [0.3974, 0.5654, 0.6709, 0.9384]]])

In [16]:
random_tensor.ndim, random_tensor.shape

(3, torch.Size([1, 3, 4]))

In [17]:
# create a random tensor with similear shape to an image
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zeros and ones

In [18]:
# create all zeros tensor
zeros = torch.zeros(size=(3,4))
zeros.ndim, zeros.shape

(2, torch.Size([3, 4]))

In [19]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones.ndim, ones.shape

(2, torch.Size([3, 4]))

In [21]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# use torch.range()
# start, end, step
ott = torch.arange(0,10,2)
ott

tensor([0, 2, 4, 6, 8])

In [23]:
# creating tensors like another array
tenzeros = torch.zeros_like(ott)
tenzeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

In [24]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None,
                                              device=None,
                                              requires_grad=False)
float_32_tensor.device

device(type='cpu')

In [25]:
float_16 = float_32_tensor.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_16 * float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32) 
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information From Tensors

1. Get dataype tensor.dtype
2. Get shape tensor.shape
3. Get device tensor.device

### Manipulating Tensors (tensor operations)

* Addition 
* Substraction
* Multiplication(element-vise)
* Division
* Matrix Multiplication

In [30]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [31]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [32]:
tensor - 10

tensor([-9, -8, -7])

In [33]:
torch.mul(tensor,10)

tensor([10, 20, 30])

## Matrix Multiplication

Two ways:
1. Element Vise
2. Matirx multiplication( dot product )

In [34]:
# Element Vise
tensor * tensor 

tensor([1, 4, 9])

In [35]:
%%time
torch.matmul(tensor, tensor), tensor

CPU times: user 1.01 ms, sys: 72 μs, total: 1.08 ms
Wall time: 2.87 ms


(tensor(14), tensor([1, 2, 3]))

### One of the most common erros in deep learning: shape errors

In [36]:
# torch.matmul(torch.rand(3,2),torch.rand(3,2)) # Error
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.8684, 0.9367],
        [1.0374, 1.1320]])

In [37]:
torch_A = torch.tensor([[1,2],[3,4],[5,6]])
torch_B = torch.tensor([[7,10],[8,11],[9,12]])

# torch.matmul(torch_A,torch_B) # Error

### Manipulate Shapes

tensor.T will transpose the matrix 

In [38]:
torch.matmul(torch_A.T,torch_B)

tensor([[ 76, 103],
        [100, 136]])

### Finding the min, max , mean, sum, etc(tensor aggregation)

In [39]:
x = torch.arange(0, 100 , 10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [40]:
# find Min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [41]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [44]:
# torch.mean() require tensor of float32
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [45]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding positional min max

In [46]:
x.argmin(), x.argmax()
# Returns the index postion of the min , max element

(tensor(0), tensor(9))

### Reshaping, Stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a an input tensosr of cetain shape but keep the same merory as the original tensor
* stacking - combine multiple tensors on top of each other  or side by side (hstack)
* squeeze - removes all '1' dimensions from tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [47]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [49]:
# change the view 
z = x.view(1,9)
z, z.shape
# here z shares the same memory as x so changing z means changing x or vice versa

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
z[:, 0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [58]:
# Stack tensors on top of each other 
x_stacked = torch.stack([x,x,x,x], dim =1) # or dim =0
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() removes all the single dimensions from target tensor
x_squeeze = torch.squeeze(x)
x_squeeze

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
print(x_reshaped)
x_reshaped.shape

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


torch.Size([1, 9])

In [64]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [69]:
# torch.unsqueeze() add a single demension to a target tensor at a specific dimension
x_reshaped.squeeze().unsqueeze(dim = 1), x_reshaped.squeeze().unsqueeze(dim = 1).shape 

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# torch.permute() rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(224,224,3) # [height, width, color]
x_premute = x_original.permute(2, 0, 1) # [colour, height, width]
x_premute.shape , x_original.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

## Indexing (Selecting data from tensors)
indexing with pytorch is similar to indexing with Numpy

In [73]:
import torch
x = torch .arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [75]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [76]:
# Lets index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [77]:
# lets index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [78]:
# you can use : to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [79]:
x[:, : ,1]

tensor([[2, 5, 8]])

In [80]:
# get all values of the 0 dim but only 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [81]:
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

* torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
* torch.Tensor.numpy() - PyTorch tensor -> NumPy array.


In [87]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [88]:
# Change the value of array, what will this do to tensor?
array = array +1
tensor, array

(tensor([1., 2., 3., 4., 5., 6., 7.]), array([2., 3., 4., 5., 6., 7., 8.]))

In [89]:
tensor.numpy()

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

## Reproducbility (Trying to take random out of random)
In short how a neural network learns:

to reduce randomness variability we use random seed

In [93]:
import torch 

random_tensor_A = torch.rand (3,4)
random_tensor_B = torch.rand (3,4)

random_tensor_A , random_tensor_B

(tensor([[0.8124, 0.3124, 0.8125, 0.2205],
         [0.5376, 0.0601, 0.0825, 0.6946],
         [0.1183, 0.7003, 0.5444, 0.4690]]),
 tensor([[0.0995, 0.2584, 0.6662, 0.7675],
         [0.2328, 0.4033, 0.8491, 0.8117],
         [0.6352, 0.5982, 0.3338, 0.3439]]))

In [98]:
# lets make some reproducable random seed
import torch
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)


random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)

random_tensor_c == random_tensor_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [99]:
## Running tensors and pytorch on the GPUs
!nvidia-smi

Wed Dec 18 16:10:05 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        Off |   00000000:01:00.0  On |                  N/A |
|  0%   31C    P8             16W /  170W |     633MiB /  12288MiB |      5%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [100]:
import torch
torch.cuda.is_available()

True

In [101]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [102]:
# count number of GPUs
torch.cuda.device_count()

1

## Putting tensors(and models) on the GPU


In [103]:
tensor = torch.tensor([1,2,3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [105]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [107]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises
All of the exercises are focused on practicing the code above.

You should be able to complete them by referencing each section or by following the resource(s) linked.

Resources:

Exercise template notebook for 00.
Example solutions notebook for 00 (try the exercises before looking at this).
1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.
2. Create a random tensor with shape (7, 7).
3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
4. Set the random seed to 0 and do exercises 2 & 3 over again.
5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
8. Find the maximum and minimum values of the output of 7.
9. Find the maximum and minimum index values of the output of 7.
10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


In [110]:
# Question 2:
random_tensor = torch.rand(7,7)
random_tensor , random_tensor.shape

(tensor([[0.3227, 0.0162, 0.2137, 0.6249, 0.4340, 0.1371, 0.5117],
         [0.1585, 0.0758, 0.2247, 0.0624, 0.1816, 0.9998, 0.5944],
         [0.6541, 0.0337, 0.1716, 0.3336, 0.5782, 0.0600, 0.2846],
         [0.2007, 0.5014, 0.3139, 0.4654, 0.1612, 0.1568, 0.2083],
         [0.3289, 0.1054, 0.9192, 0.4008, 0.9302, 0.6558, 0.0766],
         [0.8460, 0.3624, 0.3083, 0.0850, 0.0029, 0.6431, 0.3908],
         [0.6947, 0.0897, 0.8712, 0.1330, 0.4137, 0.6044, 0.7581]]),
 torch.Size([7, 7]))

In [111]:
# Question 3:
Ans_Matrix = torch.matmul(random_tensor,torch.rand(1,7).T)
Ans_Matrix, Ans_Matrix.shape

(tensor([[0.9694],
         [0.8496],
         [1.0770],
         [1.1261],
         [1.3105],
         [1.5322],
         [1.3691]]),
 torch.Size([7, 1]))

In [ ]:
# Question 4:
torch.manual_seed(0)
random_tensor = torch.rand(7,7)
print(random_tensor , random_tensor.shape)

torch.manual_seed(0)
Ans_Matrix = torch.matmul(random_tensor,torch.rand(1,7).T)
print(Ans_Matrix, Ans_Matrix.shape)

tensor([[0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
        [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237],
        [0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967]]) torch.Size([7, 7])
tensor([[2.4911],
        [2.1696],
        [1.5092],
        [1.6439],
        [2.3490],
        [1.4221],
        [1.1739]]) torch.Size([7, 1])


In [ ]:
# Question 5:
torch.cuda.manual_seed(1234)

In [123]:
# Question 6:
torch.cuda.manual_seed(1234)
tensor_one = torch.rand(2,3,device="cuda")
torch.cuda.manual_seed(1234)
tensor_two = torch.rand(2,3,device="cuda")
tensor_one , tensor_one.shape, tensor_two, tensor_two.shape

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 torch.Size([2, 3]),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 torch.Size([2, 3]))

In [124]:
# Question 7:
gpu_mutiply_matrix = torch.matmul(tensor_one, tensor_two.T)
gpu_mutiply_matrix, gpu_mutiply_matrix.shape

(tensor([[0.9792, 0.8358],
         [0.8358, 1.4578]], device='cuda:0'),
 torch.Size([2, 2]))

In [125]:
# Question 8:
gpu_mutiply_matrix.max(), gpu_mutiply_matrix.min()

(tensor(1.4578, device='cuda:0'), tensor(0.8358, device='cuda:0'))

In [129]:
# Question 9:
gpu_mutiply_matrix.argmax(), gpu_mutiply_matrix.argmin()

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [130]:
# Question 10:
torch.cuda.manual_seed(7)
random_tensor_n = torch.rand(1,1,1,10,device="cuda")
random_tensor_squeezed = random_tensor_n.squeeze()
random_tensor_n, random_tensor_n.shape, random_tensor_squeezed, random_tensor_squeezed.shape

(tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
            0.6333, 0.5733]]]], device='cuda:0'),
 torch.Size([1, 1, 1, 10]),
 tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
         0.5733], device='cuda:0'),
 torch.Size([10]))